name: OceanWATERS-coverity
on:
  schedule:
    - cron: '0 */1 * * *'
  push:
    branches: [ master, melodic-devel ]
jobs:
  scan:
    runs-on: ubuntu-latest
    continue-on-error: true
    container: oceanwaters/builder:ros-melodic-desktop-full
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - run: |
          git submodule foreach git checkout ${GITHUB_REF##*/}
          git submodule update --remote --merge
      - name: Download Coverity Build Tool
        run: |
          wget -q https://scan.coverity.com/download/linux64 --post-data "token=$TOKEN&project=Samahu%2FOceanWATERS" -O cov-analysis-linux64.tar.gz
          mkdir cov-analysis-linux64
          tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
      - name: Build PLEXIL
        run: ./build_plexil.sh
      - name: Build OceanWATERS(coverity)
        run: |
          export PATH=`pwd`/cov-analysis-linux64/bin:$PATH
          cov-build --dir cov-int ./catkin_build_oceanwaters.sh
      - uses: actions/upload-artifact@v2
        with:
          name: OceanWATERS-${{ github.run_id }}-coverity
          path: cov-int
      - name: Submit the result to Coverity Scan
        run: |
          tar czvf oceanwaters.tgz cov-int
          curl \
            --form token=$TOKEN \
            --form email=usa.naal@gmail.com \
            --form file=@oceanwaters.tgz \
            --form version="TODO Version" \
            --form description="TODO Description" \
            https://scan.coverity.com/builds?project=Samahu%2FOceanWATERS
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}