name: OceanWATERS-docker

on:
  schedule:
    - cron:  '0 6 * * *'
  push:
    branches: [ melodic-devel ]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.config.experimental }}
    strategy:
      matrix:
        config:
          - { base_image: 'ubuntu:18.04', ros_distro: melodic, ros_distro_postfix: 'ros-base', experimental: false, gpu: '' }
          - { base_image: 'ubuntu:20.04', ros_distro: noetic, ros_distro_postfix: 'ros-base', experimental: true, gpu: '' }
          - { base_image: 'nvidia/cuda:10.0-base-ubuntu18.04', ros_distro: melodic, ros_distro_postfix: 'ros-base', experimental: false, gpu: -nvidia }
          - { base_image: 'rocm/dev-ubuntu-18.04', ros_distro: melodic, ros_distro_postfix: 'ros-base', experimental: true, gpu: -amd }
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
    - name: Setup Docker BuildX
      uses: docker/setup-buildx-action@v1
    - name: DockerHub Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build & Push OceanWATER Builder
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        build-args: |
          BASE_DOCKER_IMAGE=${{ matrix.config.base_image }}
          ROS_DISTRO=${{ matrix.config.ros_distro }}
          ROS_DISTRO_POSTFIX=${{ matrix.config.ros_distro_postfix }}
        push: true
        tags: oceanwaters/builder:ros-${{ matrix.config.ros_distro }}-${{ matrix.config.ros_distro_postfix }}${{ matrix.config.gpu }}
        target: oceanwaters_builder
    - name: Build & Push OceanWATER Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        build-args: |
          BASE_DOCKER_IMAGE=${{ matrix.config.base_image }}
          ROS_DISTRO=${{ matrix.config.ros_distro }}
          ROS_DISTRO_POSTFIX=${{ matrix.config.ros_distro_postfix }}
        push: true
        tags: oceanwaters/oceanwaters:ros-${{ matrix.config.ros_distro }}-${{ matrix.config.ros_distro_postfix }}${{ matrix.config.gpu }}
        target: oceanwaters_docker