name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.config.experimental }}
    strategy:
      matrix:
        config:
          - { ubuntu_version: 18.04, ros_distro: melodic, experimental: false }
          - { ubuntu_version: 20.04, ros_distro: noetic, experimental: true }
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
    - name: Setup Docker BuildX
      uses: docker/setup-buildx-action@v1
    - name: DockerHub Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build & Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        build-args: BASE_DOCKER_IMAGE=ubuntu:${{ matrix.config.ubuntu_version }}, ROS_DISTRO=${{ matrix.config.ros_distro }}
        push: true
        tags: oceanwaters/builder:ros-${{ matrix.config.ros_distro }}-desktop-full