name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [18.04, 18.10]
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: oceanwaters/builder
        build_args: BASE_DOCKER_IMAGE=ubuntu:${{matrix.tag }}
        tags: ubuntu_${{ matrix.tag }}