name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['18.04', '18.10']
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
    - name: Setup Docker BuildX
      uses: docker/setup-buildx-action@v1
    - name: DockerHub Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build & Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        build-args: BASE_DOCKER_IMAGE='ubuntu:${{ matrix.tag }}'
        tags: 'oceanwaters/builder:ubuntu_${{ matrix.tag }}'