name: OceanWATERS

on:
  schedule:
    - cron:  '0 0 7 1/1 * ? *'
  push:
    branches: [ master, melodic-devel ]

jobs:
  build:
    runs-on: [ubuntu-18.04]
    container: oceanwaters/builder:ros-melodic-desktop-full
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: ./build_plexil.sh
      - run: ./catkin_build_oceanwaters.sh
      - uses: actions/upload-artifact@v2
        with:
          name: OceanWATERS-${{ github.run_id }}
          path: src

  test:
    runs-on: [ubuntu-18.04]
    container: oceanwaters/builder:ros-melodic-desktop-full
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: ./build_plexil.sh
      - run: ./test_oceanwaters.sh
      - uses: actions/upload-artifact@v2
        with:
          name: test-logs-${{ github.run_id }}
          path: build