on: [push, pull_request]
jobs:
  lets-build:
    runs-on: [ubuntu-18.04]
    container: oceanwaters/builder:ros-melodic-desktop-full
    steps:
      - run: mkdir src       
      - uses: actions/checkout@v2
        with:
          repository: 'nasa/ow_simulator'
          path: src/ow_simulator
      - run: catkin init
      - run: catkin build
