name: OceanWATERS

on:
  schedule:
    - cron:  '0 */1 * * *'
  push:
    branches: [ master, melodic-devel ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: oceanwaters/builder:ros-melodic-desktop-full
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/upload-artifact@v2  # upload the artifact before build occurs to avoid uploading cspice data files
        with:
          name: OceanWATERS-${{ github.run_id }}
          path: src
      - run: ./build_plexil.sh
      - run: ./catkin_build_oceanwaters.sh

  test:
    runs-on: ubuntu-latest
    container: oceanwaters/builder:ros-melodic-desktop-full
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: ./build_plexil.sh
      - run: ./test_oceanwaters.sh
      - uses: actions/upload-artifact@v2
        with:
          name: OceanWATERS-${{ github.run_id }}-test-logs
          path: build