name: Build OceanWATERS
on:
  push:
  pull_request:
    types: closed
    branches:
      - master
jobs:
  lets-build:
    runs-on: [ubuntu-18.04]
    container: oceanwaters/builder:ros-melodic-desktop-full
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - run: ls
      - run: ./build_plexil.sh
      - run: mkdir src
      - run: ./build_oceanwaters.sh
