name: OceanWATERS

on:
  schedule:
    - cron:  '0 */1 * * *'
  push:
    branches: [ master, melodic-devel ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: oceanwaters/builder:ros-melodic-desktop-full
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - run: |
          git submodule foreach git checkout ${GITHUB_REF##*/}
          git submodule update --remote --merge
      - uses: actions/upload-artifact@v2  # upload the artifact before build occurs to avoid uploading cspice data files
        with:
          name: OceanWATERS-${{ github.run_id }}
          path: src
      - name: Build PLEXIL
        run: ./build_plexil.bash
      - name: Build OceanWATERS
        run: ./catkin_build_oceanwaters.bash

  test:
    runs-on: ubuntu-latest
    container: oceanwaters/builder:ros-melodic-desktop-full
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - run: |
          git submodule foreach git checkout ${GITHUB_REF##*/}
          git submodule update --remote --merge
      - run: ./build_plexil.bash
      - run: ./test_oceanwaters.bash
      - uses: actions/upload-artifact@v2
        with:
          name: OceanWATERS-${{ github.run_id }}-test-logs
          path: build